language: java
os: linux
dist: trusty

jobs:
  include:
    - stage: v8
      jdk: oraclejdk8
      script:
        - cd AssertExtensions
        - mvn clean
        - mvn compile
        - mvn package
        - mvn test
        - mvn cobertura:cobertura
        - bash <(curl -s https://codecov.io/bash)
    - stage: v9
      jdk: oraclejdk9
      script:
        - cd AssertExtensions
        - mvn clean
        - mvn test
    - stage: v7
      jdk: openjdk7
      script:
        - cd AssertExtensions
        - mvn clean
        - mvn test
 
