language: java
os: linux
dist: trusty

jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk7

script:
  - cd AssertExtensions
  - mvn clean
  - mvn compile
  - mvn package
  - mvn cobertura:cobertura
  - mvn test

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
